// <auto-generated />
namespace TaskManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version110 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version110));
        
        string IMigrationMetadata.Id
        {
            get { return "201907030411052_version 1.1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
